name: Build Linux Plugin

on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install compiler
        run: |
          sudo apt update
          sudo apt install -y g++ make

      - name: Show project files
        run: |
          pwd
          ls -R

      - name: Build plugin
        run: |
          mkdir -p plugins
          g++ -shared -fPIC \
            src/*.cpp \
            -o plugins/vehlimit.so

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: vehlimit-linux
          path: plugins/vehlimit.so
